name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Setup Yarn
        uses: borales/actions-yarn@v4
        with: install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --run

      - name: Build
        run: yarn build
